# Generated by Django 5.2.7 on 2025-10-25 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
